config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  resources :products

  devise_for :stylists, :controllers => {
    passwords: 'stylists/passwords',
    sessions: 'stylists/sessions',
    registrations: 'stylists/registrations'
  }
  devise_for :users, :controllers => {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#welcome'
  resources :home, only: [] do
    collection{
      get :timeline
    }
  end
  get '/register_as', to:'home#register_as'
  resources :users, only: [:show]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
    @products = Product.all
    @tweets = Tweet.all
  end

  def register_as
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/register_as.html.slim
p
  - if user_signed_in?
    = link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    = link_to "一般ユーザーとして登録", new_user_registration_path
p
  - if stylist_signed_in?
    = link_to "ログアウト", destroy_user_session_path, method: :delete
  - else
    = link_to "コーディネーターとして登録", new_stylist_registration_path
a

app/views/home/timeline.html.slim
timeline.html.slim

app/views/home/welcome.html.slim
h1
  | Home#welcome
p
  | Find me in app/views/home/welcome.html.erb
p

- if user_signed_in?
  - @tweets.map do |tweet|
    = tweet.content
- elsif stylist_signed_in?
  - @products.map do |product|
    = link_to product_path(product) do
      div style="border: 1px solid #eee"
        p = image_tag product.product_photo.url, style:"height:200px;width:200px;"
        p = product.descript