config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  resources :products

  devise_for :stylists, :controllers => {
    passwords: 'stylists/passwords',
    sessions: 'stylists/sessions',
    registrations: 'stylists/registrations'
  }
  devise_for :users, :controllers => {
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'home#welcome'
  resources :home, only: [] do
    collection{
      get :timeline
    }
  end
  get '/register_as', to:'home#register_as'
  resources :users, only: [:show]

end

app/views/layouts/_header.html.slim
title
  | Styli
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav.navbar-left
      h3 タイトル
    ul.nav.navbar-nav.navbar-right
      li
        - if user_signed_in?
          = link_to "コーデを聞く", new_product_path
        - if stylist_signed_in?
          = link_to "情報発信する", new_tweet_path
      li
        - if user_signed_in? || stylist_signed_in?
          - if user_signed_in?
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          - elsif stylist_signed_in?
            = link_to "ログアウト", destroy_stylist_session_path, method: :delete
          end
        - else
          = link_to "無料登録", register_as_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Styli
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      = yield